# Site settings
title: "Lijun Zhang Resume"
description: "A resume template for Lijun Zhang and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lijun Zhang"
resume_title:                   "PHD Applicant Resume"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "zljabroad@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+86-18817870825"
resume_contact_address:         "4800 Cao’an Road, Tongji University, Shanghai, China"

resume_header_contact_info:     "4800 Cao’an Road, Tongji University, Shanghai, China • +86-18817870825 • zljabroad@outlook.com"
display_header_contact_info:    "true"

resume_header_intro1: "<p>I am a graduate student in School of Software Engneering, Tongji University, supervised by associate professor"
resume_header_intro2: "who is the leader of Computer Vision Lab in Tongji. In the postgraduate stage, my research interets are Machine Learning, Computer Vision, and Image Quality Assessment. I hope to continue my study abroad and thus I am looking for PHD position of 2019 fall. Looking forward to your contacting!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_research:        true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true

resume_section_experience:      true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/zhanglijun95"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://zhanglijun95.github.io/resume/"
  # resume_medium_url:            "zljabroad@outlook.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
